//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_des_patients
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLit : IEquatable<tblLit>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLit()
        {
            this.tblAdmissions = new HashSet<tblAdmission>();
        }
    
        public int Numérolit { get; set; }
        public bool occupé { get; set; }
        public int IDType { get; set; }
        public int IDDépartement { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAdmission> tblAdmissions { get; set; }
        public virtual tblDepartement tblDepartement { get; set; }
        public virtual tblTypeLit tblTypeLit { get; set; }

        public override bool Equals(object obj)
        {
            return Equals(obj as tblLit);
        }

        public bool Equals(tblLit other)
        {
            return other != null &&
                   Numérolit == other.Numérolit &&
                   occupé == other.occupé &&
                   IDType == other.IDType &&
                   IDDépartement == other.IDDépartement &&
                   EqualityComparer<ICollection<tblAdmission>>.Default.Equals(tblAdmissions, other.tblAdmissions) &&
                   EqualityComparer<tblDepartement>.Default.Equals(tblDepartement, other.tblDepartement) &&
                   EqualityComparer<tblTypeLit>.Default.Equals(tblTypeLit, other.tblTypeLit);
        }

       
        public static bool operator ==(tblLit left, tblLit right)
        {
            return EqualityComparer<tblLit>.Default.Equals(left, right);
        }

        public static bool operator !=(tblLit left, tblLit right)
        {
            return !(left == right);
        }
    }
}
