//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_des_patients
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPatient()
        {
            this.tblAdmissions = new HashSet<tblAdmission>();
        }
    
        public int NSS { get; set; }
        public Nullable<System.DateTime> date_naissance { get; set; }
        public string nom { get; set; }
        public string prénom { get; set; }
        public string adresse { get; set; }
        public string ville { get; set; }
        public string province { get; set; }
        public string code_postal { get; set; }
        public string téléphone { get; set; }
        public Nullable<int> IDAssurance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAdmission> tblAdmissions { get; set; }
        public virtual tblAssurance tblAssurance { get; set; }

        public tblPatient(int nSS, DateTime? date_naissance, string nom, string prénom, string adresse, string ville, string province, string code_postal, string téléphone, int? iDAssurance)
        {
            NSS = nSS;
            this.date_naissance = date_naissance;
            this.nom = nom;
            this.prénom = prénom;
            this.adresse = adresse;
            this.ville = ville;
            this.province = province;
            this.code_postal = code_postal;
            this.téléphone = téléphone;
            IDAssurance = iDAssurance;
        }

      

    }
}
