//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using System.Windows;

namespace Gestion_des_patients
{
    [Serializable]
    internal class Valid_ID_admission_insertionException : Exception
    {
        public Valid_ID_admission_insertionException()
        {
            
        }

        public Valid_ID_admission_insertionException(string message) : base(message)
        {
        }

        public Valid_ID_admission_insertionException(string message, Exception innerException) : base(message, innerException)
        {
        }

        protected Valid_ID_admission_insertionException(SerializationInfo info, StreamingContext context) : base(info, context)
        {
        }
    }
}