//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

namespace Gestion_des_patients
{
    [Serializable]
    internal class Valid_programmation_chirurgieException : Exception
    {
        public Valid_programmation_chirurgieException()
        {
        }

        public Valid_programmation_chirurgieException(string message) : base(message)
        {
        }

        public Valid_programmation_chirurgieException(string message, Exception innerException) : base(message, innerException)
        {
        }

        protected Valid_programmation_chirurgieException(SerializationInfo info, StreamingContext context) : base(info, context)
        {
        }
    }
}